### PR TITLE
#314 admins categories

### LINKED ISSUE #341: [Frontend] - Allow admins to manage categories/subcategories
As a admin, I would like to add, remove, edit categories and corresponding sub-categories.

**Description** 
Categories and subcategories should not be able to be modified by regular users but to be able to adapt to changes, there should be a way for admins to be allowed to add new categories and their corresponding subcategories. Not only this, but to be able to remove ones, and edit them.

**MOCKUP:** https://www.figma.com/file/MmvzMxb3sK8taRBxRalorD/Dataset-Review?node-id=100%3A705

**Tasks**
- [ ] Create the frontend to follow said mockup
- [ ] Connect the frontend to call the APIs to add/remove or edit
- [ ] Create snackbars for the error messages and success messages
- [ ] Validate if the category or subcategories already exist
- [ ] Connect the frontend to fetch all the categories/subcategories

**Acceptance Criteria**
Admins are able to edit, remove, add categories/subcategories
All subcategories have a corresponding category

### PR DESCRIPTION
**Pull request by GD-Dheer**
This PR adds functionality for performing CRUD operations on new categories & subcategories under the user profile

### CODE REVIEW

**Review by silent-po2 — CHANGES_REQUESTED** [review]
Upon adding or editing a category, there is no message at all after the operation finishes. As such a user has no idea if their changes were successful or not. Can a message be displayed, the page refreshed, or something to notify the user? 

Deleting a category or subcategory doesn't have a success message, but it does have a message if an item cannot be deleted.

**Review by ds161833 — APPROVED** [review]

**Review by Mehrdadmaskull — APPROVED** [review]
I'd say having snackbar messages would be nice to have too. Other than that, nice and clean code, thank you. LGTM

**Comment by GD-Dheer** [comment]
> Upon adding or editing a category, there is no message at all after the operation finishes. As such a user has no idea if their changes were successful or not. Can a message be displayed, the page refreshed, or something to notify the user?
> 
> Deleting a category or subcategory doesn't have a success message, but it does have a message if an item cannot be deleted.

When can a category not be deleted? This is an admin privilege right? All categories can be changed/modified

**Comment by silent-po2** [comment]
> When can a category not be deleted? This is an admin privilege right? All categories can be changed/modified

A category cannot be deleted if one of its subcategories is in use by a data point. Likewise a subcategory cannot be deleted for the same reason. That's the only cause

**Review by silent-po2 — APPROVED** [review]
Thanks for adding the status messages!

**Comment by GD-Dheer** [comment]
> This PR adds functionality for performing CRUD operations on new categories & subcategories under the user profile

Wrong commits were linked to this story. Should have been #341

**Pull request merged**
