### PR TITLE
Improving Backend Test Coverage, Plus Tweaks

### PR DESCRIPTION
**Pull request by silent-po2**
-Changed FileParserController from declaring things via a constructor to declaring them in a method, as is done with other controllers
-Added a handful of new tests to improve coverage and cover all backend files
-Removed some unused backend files
-Updated a few file/method names to match convention
-Set Accounts entity's admin field to be specified as tinyint there, to match DB

Test coverage is the following with these changes:
image

### CODE REVIEW

**Review by Mehrdadmaskull — APPROVED** [review]
Nice code cleanup, LGTM

**Comment by JeremiahTee** [comment]
Thank you for adding these tests in! 
Looks great, only changes to be made are the two code smells flagged by Sonarcloud (the rest are false positives)
image

**Review by JeremiahTee — CHANGES_REQUESTED** [review]
Two code smells to address, empty constructor and unused import

**Review by JeremiahTee — APPROVED** [review]
Thank you for fixing all code smells, looks great!

**Pull request merged**
