### PR TITLE
Fix failing travis encryption errors

### PR DESCRIPTION
**Pull request by GD-Dheer**
Fixes travis being unable to test to test DB to execute Unit tests

### CODE REVIEW

**Comment by GD-Dheer** [comment]
> Fixes travis being unable to test to test DB to execute Unit tests

Screen Shot 2020-12-20 at 7 38 39 PM

**Comment by JeremiahTee** [comment]
Approving as it's a really small change. Some values (the correct one being changed). Good work!

**Review by JeremiahTee — APPROVED** [review]

**Review by TiraFire — COMMENTED** [review]
Please re-write your comment for the PR, it lacks information on what problems this fixes and how this solves it in a clear way. I, knowing the problem, still have trouble reading that.

**Comment by TiraFire** [comment]
> Fixes travis being unable to test to test DB to execute Unit tests

This is the part i mean when i say to re-write it

**Comment by GD-Dheer** [comment]
> Fixes travis being unable to test to test DB to execute Unit tests

This PR addresses the issue with Travis being unable to connect to our test database. We should never pass plain text env variables for into a public yml file and public repo. Travis has an option to pass encrypted environment variables to the CI. Each 'secure' represents 1 env variable found in .env test attributes to connect to Azure

**Review by TiraFire — APPROVED** [review]

**Pull request merged**
