### PR TITLE
#226 Load test graph feature & reports

### PR DESCRIPTION
**Pull request by JeremiahTee**
This JMeter file adds the following tests for the Graph feature, which is tested by testing different search parameters:
Specific year AND category → critical energy, 1980
Specific material → H2
Specific year → 1980
Specific author → Akbar
Specific author AND year → Akbar, 1997

Figure 1.
image

From Test #4 (Fig. 1), we can see the year column that displays 1997 year. Therefore we load tests with both last name and specific year to see if there is a difference in performance.

Results: It is actually 8 seconds slower when searching by both specific Author and specific year (Akbar, 1997)

Detailed reports on Confluence:
[Graph feature load testing [Report]](https://databoom.atlassian.net/l/c/4xuYje14)

Extra:
I wrote a report for Graph page performance, tested with Lighthouse (Chrome dev tools)
[Page performance testing (Lighthouse)](https://databoom.atlassian.net/l/c/ypB2uSab)

### CODE REVIEW

**Comment by JeremiahTee** [comment]
Full report on Confluence (some screenshots) Link -> [Graph feature load testing [Report]](https://databoom.atlassian.net/l/c/4xuYje14)

image
image

**Comment by JeremiahTee** [comment]
Results of running Lighthouse on Graph page for page performance testing (Client side)
Link to report -> [Page performance testing (Lighthouse)](https://databoom.atlassian.net/l/c/ypB2uSab)
image

**Review by ds161833 — APPROVED** [review]

**Comment by ds161833** [comment]
> Results of running Lighthouse on Graph page for page performance testing (Client side)
> Link to report -> [Page performance testing (Lighthouse)](https://databoom.atlassian.net/l/c/ypB2uSab)
> image

oh nice, i will take a look at the perfomance client side, very curios i know there are some issues sometimes, good job

**Review by laithAwad — APPROVED** [review]
Great work very detailed and helpful!

**Comment by JeremiahTee** [comment]
> > Results of running Lighthouse on Graph page for page performance testing (Client side)
> > Link to report -> [Page performance testing (Lighthouse)](https://databoom.atlassian.net/l/c/ypB2uSab)
> > image
> 
> oh nice, i will take a look at the perfomance client side, very curios i know there are some issues sometimes, good job

Yess, it shows as well which steps we can take to optimize performance, from the report, we could save 0.36 + 0.32 seconds:
image
image

**Review by silent-po2 — CHANGES_REQUESTED** [review]
This is really good work. At the start of this, it became clear that there needs to be adjustments to the backend to improve search times. I have begun efforts on this matter as a result.

However, the Year+Subcategory search should be changed. This isn't a valid search; any subcategory that is sent without a category is ignored. I would suggest changing it to Year+Category with the category being cell size, aka. categoryId 2

**Comment by JeremiahTee** [comment]
> This is really good work. At the start of this, it became clear that there needs to be adjustments to the backend to improve search times. I have begun efforts on this matter as a result.
> 
> However, the Year+Subcategory search should be changed. This isn't a valid search; any subcategory that is sent without a category is ignored. I would suggest changing it to Year+Category with the category being cell size, aka. categoryId 2

You're absolutely right. When I searched for Year + Subcategory some results were returned, however this is not a valid search. As discussed, this will eventually be fixed in the front-end. I will create a bug for it.

I'm changing the test to category being critical energy (categoryId = 4) as I already did cell size for the Search loadtest

**Comment by JeremiahTee** [comment]
Pushed the fix and updated [report](https://databoom.atlassian.net/l/c/LoCRNucy)

**Review by silent-po2 — APPROVED** [review]
Thanks for the change, all good to go now.

**Pull request merged**
