### PR TITLE
Added tab titles for each page

### LINKED ISSUE #456: Have each page have it own tab title instead of generic Databoom

### PR DESCRIPTION
**Pull request by laithAwad**
Modified all the pages to show the correct title on the browser's tab

The following are examples of the tabs:

Screen Shot 2021-03-15 at 11 46 23 PM
Screen Shot 2021-03-15 at 11 46 18 PM
Screen Shot 2021-03-15 at 11 46 12 PM

### CODE REVIEW

**Review by TiraFire — APPROVED** [review]

**Review by ds161833 — CHANGES_REQUESTED** [review]
For the graph page, put the hook inside the graphview, also add an empty array dependency so that the title is only changed once on page load

**Comment by laithAwad** [comment]
> For the graph page, put the hook inside the graphview, also add an empty array dependency so that the title is only changed once on page load

Done, do i need to add empty arrays for any page other than graph?

**Comment by ds161833** [comment]
> > For the graph page, put the hook inside the graphview, also add an empty array dependency so that the title is only changed once on page load
> 
> Done, do i need to add empty arrays for any page other than graph?

Yep

**Comment by laithAwad** [comment]
> > > For the graph page, put the hook inside the graphview, also add an empty array dependency so that the title is only changed once on page load
> > 
> > 
> > Done, do i need to add empty arrays for any page other than graph?
> 
> Yep

All done now

**Review by ds161833 — APPROVED** [review]

**Pull request merged**
