### PR TITLE
#119 Sonarqube Code smell fixes in the frontend

### PR DESCRIPTION
**Pull request by JeremiahTee**
This PR fixes the Sonarqube issues raised in backend (and frontend for the bug in Blurb.css). Part of #119 

Prior to these fixes, Sonarqube displayed these metrics:
image
(Screenshot taken from [Sonarqube Reports Confluence Article](https://databoom.atlassian.net/wiki/spaces/DB/pages/27131926/Sonarqube+Reports))

38 code smells in the Frontend (Client) were documented and addressed. The detailed documentation can be found on the aforementioned Sonarqube Report (link above). 
image

Most of them were unused variables (392940b) (or imports) and changing wrapper object type to primitive type (7b8fbe2d)

Two code smells were left untouched as I believe they are false positives. To be confirmed with @TiraFire 
image

### CODE REVIEW

**Review by Mehrdadmaskull — APPROVED** [review]
Great job, LGTM

**Review by ds161833 — APPROVED** [review]
const clip =; 
remove and the rest looks good, good job on cleanin the whole thing up, everyone should install ESLint and we wouldnt need to do this cleanup later :)👍

**Comment by JeremiahTee** [comment]
As discussed with Dmytro @ds161833 , we reviewed the quality of the code on the front-end.
More specifically, we found that the quality of the code on Client/src/Components/Graph/**Graph.js** is _poor_ in terms of modularity. As a developer coming from backend, it is really hard for me to read this code because a lot of it is "bundled" together. @ds161833 said that he would refactor this code in the near-future, time-permitting. We will definitely open a refactoring issue for Dmytro to refactor this Graph.js file, and possibly other files in the front-end as well.

We concluded that it is *imperative* for front-end developers to have the following extensions installed on their machines through VS Code: **ESlint** and **AutoImport.** 
Dmytro has showed me during a PR review how to install these extensions, how they work, and why we should have them. Therefore, I will be writing a **"Front-end Coding Guideline" article** on Confluence for developers to follow. 

Moreover, Dmytro pointed out that the Blurb.css file in the front-end will be replaced in the future by App.theme. As he said, we should not have different .css files for styling, as the styling will be managed by a **single App.theme**. I presume this could also be a refactoring PR. 

The last two commits included the changes requested by @ds161833 . I am waiting on the Travis builds to pass before merging this PR.

**Comment by JeremiahTee** [comment]
Merging the pull request as the PR has been approved by two, reviewed, and the Travis CI builds have passed. I will also move the card on Zenhub accordingly. Thank you for your reviews.

**Pull request merged**
