### PR TITLE
Testing CI

### PR DESCRIPTION
**Pull request by GD-Dheer**
This is a test PR for integration of the GitHub Actions CI. CI was successfully integrated! PR is valid and gets our CI up and running

### CODE REVIEW

**Comment by JeremiahTee** [comment]
Fixed CI by adding missing environment secrets (username) in the .yml file. I also fixed the syntax, seperated into multiple jobs for clarity.
I also added mail gun environment secrets.
I added a step where it npm installs in the Client folder, should we remove it since we don't have any tests there?
Current time for build is approx. 3 min because of the additional npm install on Client.

image

**Comment by GD-Dheer** [comment]
> Fixed CI by adding missing environment secrets (username) in the .yml file. I also fixed the syntax, seperated into multiple jobs for clarity.
> I also added mail gun environment secrets.
> I added a step where it npm installs in the Client folder, should we remove it since we don't have any tests there?
> Current time for build is approx. 3 min because of the additional npm install on Client.
> 
> image

We can leave it for now since FE unit tests will be added during release 3

**Review by TiraFire — APPROVED** [review]

**Review by ds161833 — CHANGES_REQUESTED** [review]
@JeremiahTee these are needed files put them back
image
the templates and the .side file for the tests

**Comment by ds161833** [comment]
> Fixed CI by adding missing environment secrets (username) in the .yml file. I also fixed the syntax, seperated into multiple jobs for clarity.
> I also added mail gun environment secrets.
> I added a step where it npm installs in the Client folder, should we remove it since we don't have any tests there?
> Current time for build is approx. 3 min because of the additional npm install on Client.
> 
> image

Whether there are tests or not makes no difference, CI makes sure that the code builds, npm i is needed for the code to build, if there are any compilation errors it will show

**Comment by JeremiahTee** [comment]
> @JeremiahTee these are needed files put them back
> image
> the templates and the .side file for the tests

Sorry that was a mistake on my part! I fixed it by reverting the commit

**Comment by JeremiahTee** [comment]
> > Fixed CI by adding missing environment secrets (username) in the .yml file. I also fixed the syntax, seperated into multiple jobs for clarity.
> > I also added mail gun environment secrets.
> > I added a step where it npm installs in the Client folder, should we remove it since we don't have any tests there?
> > Current time for build is approx. 3 min because of the additional npm install on Client.
> > image
> 
> Whether there are tests or not makes no difference, CI makes sure that the code builds, npm i is needed for the code to build, if there are any compilation errors it will show

You're absolutely right. The current yaml file runs npm i on the client. I will leave it as it is

**Review by ds161833 — APPROVED** [review]

**Pull request merged**
