### PR TITLE
Added UI tests for all new pages

### PR DESCRIPTION
**Pull request by laithAwad**
Added all necessary UI tests for all the pages and functions added in sprint 5

Referncing #21 #24 #26 #32 #34 #38 #40 #160 issues

### CODE REVIEW

**Comment by Mehrdadmaskull** [comment]
Referncing #21 #24 #26 #32 #34 #38 #40 #160 issues

**Review by GD-Dheer — APPROVED** [review]
Nice work adding these tests. Helps a lot with our code quality

**Review by JeremiahTee — APPROVED** [review]
Thanks for adding the tests, looks good

**Review by silent-po2 — CHANGES_REQUESTED** [review]
I'm getting fails during testing, which must be addressed. Fails happen in; ChangeXScale, ChangeYScale, DataCellAnalysisPage, Deleting Dataset, Hiding Datapoints, Hiding Dataset, ResearchAnalysisPage, manualDataSetUpload, viewFavoritesTable. 

image

image

image

image

image

image

image

image

image

**Comment by Mehrdadmaskull** [comment]
Closing the PR for now, it needs to be connected to the Jenkins, and a better format would be needed for the frontend for the UI Tests which will be discussed with the front-end team.

**Comment by JeremiahTee** [comment]
After a team PR review where local machine issues were brought up, we decided to postpone this to Sprint 6 as @Mehrdadmaskull mentioned, we need to discuss with @ds161833 and rest of front-end for format. However, the bulk of the UI tests have been done. The UI tests have been written and they work on Mac OS.  It's just a matter of connection with Jenkins and better formatting as mentioned. It shouldn't take more than a day, and so it will be finished within the first week of Sprint 6.

The UI tests for these issues have been written but not completed (as mentioned above)
#36 #160 #40 #38 #32 #24
As we need to regroup and discuss as a team, I am moving theses issues to Icebox.

**Pull request closed without merging**
